code --install-extension 2gua.rainbow-brackets
code --install-extension alefragnani.Bookmarks
code --install-extension brpaz.file-templates
code --install-extension cometeer.spacemacs
code --install-extension EditorConfig.EditorConfig
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension Equinusocio.vsc-material-theme
code --install-extension formulahendry.code-runner
code --install-extension ms-python.python
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension njpwerner.autodocstring
code --install-extension PeterJausovec.vscode-docker
code --install-extension robertohuertasm.vscode-icons
code --install-extension shardulm94.trailing-spaces
code --install-extension SonarSource.sonarlint-vscode
code --install-extension spywhere.guides
code --install-extension thomaspink.theme-github
code --install-extension timonwong.shellcheck
code --install-extension yzhang.markdown-all-in-one

